# Generated by Django 5.2.8 on 2026-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='size',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
